name: Auto Update IPTV Playlist

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Download Latest Playlist
        run: |
          curl -s https://iptv-org.github.io/iptv/countries/id.m3u -o playlist.m3u
          
      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action Bot"
          git add playlist.m3u
          git commit -m "Update otomatis link TV" || echo "Tidak ada perubahan"
          git push
